server:
  port: 7070


spring:
  application:
    name: config-serve
  cloud:
    config:
      server:
        git:
          uri: https://github.com/olgeradriano/xd.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main

  security:
    user:
      name: root
      password: 123456


