#spring.application.name=ms-catalogo


# CONEXION A BASE DE DATOS
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/ms_catalogo
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#
#
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/doc/swagger-ui.html
#




#
#server:
#  port: 8081
#spring:
#  application:
#    name: ms-catalogo
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms_catalogo
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html



spring:
  application:
    name: ms-catalogo-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070



